/*
 * This file is part of Compass.
 * Copyright (C) 2026 Philipp Bobek <philipp.bobek@mailbox.org>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Compass is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.bobek.compass.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006B5F)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF9EF2E3)
val onPrimaryContainerLight = Color(0xFF005047)
val secondaryLight = Color(0xFF4A635E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCCE8E2)
val onSecondaryContainerLight = Color(0xFF334B47)
val tertiaryLight = Color(0xFF456179)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFCBE6FF)
val onTertiaryContainerLight = Color(0xFF2D4A60)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF4FBF8)
val onBackgroundLight = Color(0xFF171D1B)
val surfaceLight = Color(0xFFF4FBF8)
val onSurfaceLight = Color(0xFF171D1B)
val surfaceVariantLight = Color(0xFFDAE5E1)
val onSurfaceVariantLight = Color(0xFF3F4946)
val outlineLight = Color(0xFF6F7976)
val outlineVariantLight = Color(0xFFBEC9C5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B3230)
val inverseOnSurfaceLight = Color(0xFFECF2EF)
val inversePrimaryLight = Color(0xFF82D5C7)
val surfaceDimLight = Color(0xFFD5DBD9)
val surfaceBrightLight = Color(0xFFF4FBF8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5F2)
val surfaceContainerLight = Color(0xFFE9EFEC)
val surfaceContainerHighLight = Color(0xFFE3EAE7)
val surfaceContainerHighestLight = Color(0xFFDDE4E1)

val primaryLightMediumContrast = Color(0xFF003E37)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF1E7A6E)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF223B36)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF59726D)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF1B394F)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF547088)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF4FBF8)
val onBackgroundLightMediumContrast = Color(0xFF171D1B)
val surfaceLightMediumContrast = Color(0xFFF4FBF8)
val onSurfaceLightMediumContrast = Color(0xFF0C1211)
val surfaceVariantLightMediumContrast = Color(0xFFDAE5E1)
val onSurfaceVariantLightMediumContrast = Color(0xFF2F3836)
val outlineLightMediumContrast = Color(0xFF4B5452)
val outlineVariantLightMediumContrast = Color(0xFF656F6C)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2B3230)
val inverseOnSurfaceLightMediumContrast = Color(0xFFECF2EF)
val inversePrimaryLightMediumContrast = Color(0xFF82D5C7)
val surfaceDimLightMediumContrast = Color(0xFFC1C8C5)
val surfaceBrightLightMediumContrast = Color(0xFFF4FBF8)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFEFF5F2)
val surfaceContainerLightMediumContrast = Color(0xFFE3EAE7)
val surfaceContainerHighLightMediumContrast = Color(0xFFD8DEDB)
val surfaceContainerHighestLightMediumContrast = Color(0xFFCDD3D0)

val primaryLightHighContrast = Color(0xFF00332C)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF00534A)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF18302C)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF354E49)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF0F2F44)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF2F4C63)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF4FBF8)
val onBackgroundLightHighContrast = Color(0xFF171D1B)
val surfaceLightHighContrast = Color(0xFFF4FBF8)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDAE5E1)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF252E2C)
val outlineVariantLightHighContrast = Color(0xFF414B49)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2B3230)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFF82D5C7)
val surfaceDimLightHighContrast = Color(0xFFB4BAB8)
val surfaceBrightLightHighContrast = Color(0xFFF4FBF8)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFECF2EF)
val surfaceContainerLightHighContrast = Color(0xFFDDE4E1)
val surfaceContainerHighLightHighContrast = Color(0xFFCFD6D3)
val surfaceContainerHighestLightHighContrast = Color(0xFFC1C8C5)

val primaryDark = Color(0xFF82D5C7)
val onPrimaryDark = Color(0xFF003731)
val primaryContainerDark = Color(0xFF005047)
val onPrimaryContainerDark = Color(0xFF9EF2E3)
val secondaryDark = Color(0xFFB1CCC6)
val onSecondaryDark = Color(0xFF1C3530)
val secondaryContainerDark = Color(0xFF334B47)
val onSecondaryContainerDark = Color(0xFFCCE8E2)
val tertiaryDark = Color(0xFFACCAE5)
val onTertiaryDark = Color(0xFF143349)
val tertiaryContainerDark = Color(0xFF2D4A60)
val onTertiaryContainerDark = Color(0xFFCBE6FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0E1513)
val onBackgroundDark = Color(0xFFDDE4E1)
val surfaceDark = Color(0xFF0E1513)
val onSurfaceDark = Color(0xFFDDE4E1)
val surfaceVariantDark = Color(0xFF3F4946)
val onSurfaceVariantDark = Color(0xFFBEC9C5)
val outlineDark = Color(0xFF899390)
val outlineVariantDark = Color(0xFF3F4946)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDDE4E1)
val inverseOnSurfaceDark = Color(0xFF2B3230)
val inversePrimaryDark = Color(0xFF006B5F)
val surfaceDimDark = Color(0xFF0E1513)
val surfaceBrightDark = Color(0xFF343B39)
val surfaceContainerLowestDark = Color(0xFF090F0E)
val surfaceContainerLowDark = Color(0xFF171D1B)
val surfaceContainerDark = Color(0xFF1A211F)
val surfaceContainerHighDark = Color(0xFF252B2A)
val surfaceContainerHighestDark = Color(0xFF303634)

val primaryDarkMediumContrast = Color(0xFF98ECDD)
val onPrimaryDarkMediumContrast = Color(0xFF002B26)
val primaryContainerDarkMediumContrast = Color(0xFF4B9E91)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFC6E2DC)
val onSecondaryDarkMediumContrast = Color(0xFF112A26)
val secondaryContainerDarkMediumContrast = Color(0xFF7C9690)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFC2E0FC)
val onTertiaryDarkMediumContrast = Color(0xFF06283D)
val tertiaryContainerDarkMediumContrast = Color(0xFF7794AE)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0E1513)
val onBackgroundDarkMediumContrast = Color(0xFFDDE4E1)
val surfaceDarkMediumContrast = Color(0xFF0E1513)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF3F4946)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD4DFDB)
val outlineDarkMediumContrast = Color(0xFFAAB4B1)
val outlineVariantDarkMediumContrast = Color(0xFF88928F)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDDE4E1)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF252B2A)
val inversePrimaryDarkMediumContrast = Color(0xFF005248)
val surfaceDimDarkMediumContrast = Color(0xFF0E1513)
val surfaceBrightDarkMediumContrast = Color(0xFF3F4644)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF040807)
val surfaceContainerLowDarkMediumContrast = Color(0xFF181F1D)
val surfaceContainerDarkMediumContrast = Color(0xFF232928)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2D3432)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF383F3D)

val primaryDarkHighContrast = Color(0xFFB0FFF0)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF7FD1C3)
val onPrimaryContainerDarkHighContrast = Color(0xFF000E0B)
val secondaryDarkHighContrast = Color(0xFFDAF6EF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFADC8C2)
val onSecondaryContainerDarkHighContrast = Color(0xFF000E0B)
val tertiaryDarkHighContrast = Color(0xFFE5F1FF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFA9C6E1)
val onTertiaryContainerDarkHighContrast = Color(0xFF000C18)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF0E1513)
val onBackgroundDarkHighContrast = Color(0xFFDDE4E1)
val surfaceDarkHighContrast = Color(0xFF0E1513)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF3F4946)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFE8F2EF)
val outlineVariantDarkHighContrast = Color(0xFFBAC5C1)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDDE4E1)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF005248)
val surfaceDimDarkHighContrast = Color(0xFF0E1513)
val surfaceBrightDarkHighContrast = Color(0xFF4B5150)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1A211F)
val surfaceContainerDarkHighContrast = Color(0xFF2B3230)
val surfaceContainerHighDarkHighContrast = Color(0xFF363D3B)
val surfaceContainerHighestDarkHighContrast = Color(0xFF424846)
